### ISSUE TITLE
랭킹 페이지 sqlite3 등록 정보들 가져오는 방법 필요

### ISSUE THREAD

**Issue by jihyewlgP** [KDT-project-team-B/travel-assistant#4]
sqlite3에 총 12개의 파일 중 2개 업데이트 후 테스트 결과 데이터가 보이지 않음...

**Comment by SEOJIN-Lab** [comment]
이게 연동이 아예 안되는 것 같다는 말씀이시죠?

**Comment by jihyewlgP** [comment]
네.... 그리고 html 도 화면에 안떠서...

**Comment by jihyewlgP** [comment]
네 .. 제가 뭘 잘못했을 것 같긴한데 지금 어디가 잘못된지 모르겠는 상태에요..
